IF OBJECT_ID('trg_TableChange', 'TR') IS NOT NULL
    DROP TRIGGER trg_TableChange ON DATABASE;
GO

CREATE TRIGGER trg_TableChange
ON DATABASE
FOR CREATE_TABLE, ALTER_TABLE, DROP_TABLE
AS
BEGIN
    PRINT 'Tabeli struktuur on muutunud.'
END;
GO